use std::collections::HashMap;

use cranelift_codegen::ir::{FuncRef, Value};
use cranelift_module::Module;

use crate::mir::{MirContinuationId, MirFunction, MirFunctionId, MirScopeId, MirTaskId};
use crate::sema::{Type, TypeTable};

use super::super::super::environment::FunctionType;

#[derive(Clone, Copy)]
pub(crate) struct RuntimeRefs {
    pub(crate) calls: RuntimeCallRefs,
    pub(crate) continuation_alloc_suspend_result: FuncRef,
    pub(crate) continuation_release_suspend_result: FuncRef,
    pub(crate) continuation_clear_suspend_cleanups: FuncRef,
    pub(crate) continuation_register_cleanup: FuncRef,
    pub(crate) continuation_register_cleanup_region: FuncRef,
    pub(crate) continuation_complete: FuncRef,
    pub(crate) continuation_complete_function_pending: FuncRef,
    pub(crate) continuation_start_pending_timer: FuncRef,
    pub(crate) continuation_start_pending_provider: FuncRef,
    pub(crate) continuation_set_program_counter: FuncRef,
    pub(crate) continuation_resume_at: FuncRef,
    pub(crate) continuation_complete_suspend: FuncRef,
    pub(crate) continuation_suspend_result_pointer: FuncRef,
}

#[derive(Clone, Copy)]
pub(crate) struct RuntimeCallRefs {
    pub(crate) hasher_new: FuncRef,
    pub(crate) hasher_word: FuncRef,
    pub(crate) hasher_string: FuncRef,
    pub(crate) hasher_bytes: FuncRef,
    pub(crate) hasher_finish: FuncRef,
    pub(crate) cown_new: FuncRef,
    pub(crate) cown_acquire: FuncRef,
    pub(crate) cown_acquire_many: FuncRef,
    pub(crate) cown_payload: FuncRef,
    pub(crate) cown_release: FuncRef,
    pub(crate) print: FuncRef,
    pub(crate) println: FuncRef,
    pub(crate) panic: FuncRef,
    pub(crate) allocate: FuncRef,
    pub(crate) closure_allocate: FuncRef,
    pub(crate) dup: FuncRef,
    pub(crate) managed_drop: FuncRef,
    pub(crate) string_from: FuncRef,
    pub(crate) bytes_from_data: FuncRef,
    pub(crate) string_len: FuncRef,
    pub(crate) string_c_string_check: FuncRef,
    pub(crate) string_from_cstr: FuncRef,
    pub(crate) c_alloc: FuncRef,
    pub(crate) c_free: FuncRef,
    pub(crate) callback_function: FuncRef,
    pub(crate) callback_context: FuncRef,
    pub(crate) callback_failed: FuncRef,
    pub(crate) show_i64: FuncRef,
    pub(crate) debug_path: FuncRef,
    pub(crate) debug_path_status: FuncRef,
    pub(crate) debug_native_id: FuncRef,
    pub(crate) debug_string: FuncRef,
    pub(crate) debug_bytes: FuncRef,
    pub(crate) debug_duration: FuncRef,
    pub(crate) echo: FuncRef,
    pub(crate) show_u64: FuncRef,
    pub(crate) show_f64: FuncRef,
    pub(crate) show_bool: FuncRef,
    pub(crate) string_concat: FuncRef,
    pub(crate) string_eq: FuncRef,
    pub(crate) string_compare: FuncRef,
    pub(crate) string_starts_with: FuncRef,
    pub(crate) string_ends_with: FuncRef,
    pub(crate) string_contains: FuncRef,
    pub(crate) string_scalar_count: FuncRef,
    pub(crate) string_grapheme_count: FuncRef,
    pub(crate) string_is_ascii: FuncRef,
    pub(crate) string_trim: FuncRef,
    pub(crate) string_to_upper: FuncRef,
    pub(crate) string_to_lower: FuncRef,
    pub(crate) string_split: FuncRef,
    pub(crate) path_call: FuncRef,
    pub(crate) string_replace: FuncRef,
    pub(crate) string_get_byte: FuncRef,
    pub(crate) string_slice: FuncRef,
    pub(crate) parse_i8: FuncRef,
    pub(crate) parse_i16: FuncRef,
    pub(crate) parse_i64: FuncRef,
    pub(crate) parse_u8: FuncRef,
    pub(crate) parse_u16: FuncRef,
    pub(crate) parse_u32: FuncRef,
    pub(crate) parse_u64: FuncRef,
    pub(crate) parse_f32: FuncRef,
    pub(crate) parse_bool: FuncRef,
    pub(crate) parse_i32: FuncRef,
    pub(crate) parse_f64: FuncRef,
    pub(crate) batch_new: FuncRef,
    pub(crate) batch_worker: FuncRef,
    pub(crate) batch_next: FuncRef,
    pub(crate) batch_push: FuncRef,
    pub(crate) batch_finish: FuncRef,
    pub(crate) seq_new: FuncRef,
    pub(crate) seq_push: FuncRef,
    pub(crate) seq_finish: FuncRef,
    pub(crate) list_cons: FuncRef,
    pub(crate) list_head: FuncRef,
    pub(crate) list_tail: FuncRef,
    pub(crate) list_length: FuncRef,
    pub(crate) list_reverse: FuncRef,
    pub(crate) mut_list_new: FuncRef,
    pub(crate) mut_list_push: FuncRef,
    pub(crate) mut_list_get: FuncRef,
    pub(crate) mut_list_set: FuncRef,
    pub(crate) mut_list_pop: FuncRef,
    pub(crate) mut_list_length: FuncRef,
    pub(crate) mut_list_capacity: FuncRef,
    pub(crate) mut_list_cursor_new: FuncRef,
    pub(crate) mut_list_cursor_step: FuncRef,
    pub(crate) mut_list_to_list: FuncRef,
    pub(crate) map_insert: FuncRef,
    pub(crate) map_get: FuncRef,
    pub(crate) map_remove: FuncRef,
    pub(crate) map_contains_key: FuncRef,
    pub(crate) map_length: FuncRef,
    pub(crate) map_cursor_new: FuncRef,
    pub(crate) map_cursor_step: FuncRef,
    pub(crate) mut_map_new: FuncRef,
    pub(crate) mut_map_insert: FuncRef,
    pub(crate) mut_map_get: FuncRef,
    pub(crate) mut_map_remove: FuncRef,
    pub(crate) mut_map_contains_key: FuncRef,
    pub(crate) mut_map_length: FuncRef,
    pub(crate) mut_map_capacity: FuncRef,
    pub(crate) mut_map_is_empty: FuncRef,
    pub(crate) mut_map_cursor_new: FuncRef,
    pub(crate) mut_map_cursor_step: FuncRef,
    pub(crate) mut_map_to_list: FuncRef,
    pub(crate) bytes_new: FuncRef,
    pub(crate) bytes_from_string: FuncRef,
    pub(crate) bytes_eq: FuncRef,
    pub(crate) bytes_compare: FuncRef,
    pub(crate) bytes_length: FuncRef,
    pub(crate) bytes_cursor_new: FuncRef,
    pub(crate) bytes_cursor_step: FuncRef,
    pub(crate) mut_bytes_new: FuncRef,
    pub(crate) mut_bytes_with_capacity: FuncRef,
    pub(crate) mut_bytes_length: FuncRef,
    pub(crate) mut_bytes_capacity: FuncRef,
    pub(crate) mut_bytes_push: FuncRef,
    pub(crate) bytes_is_empty: FuncRef,
    pub(crate) bytes_get: FuncRef,
    pub(crate) bytes_slice: FuncRef,
    pub(crate) bytes_concat: FuncRef,
    pub(crate) bytes_to_string: FuncRef,
    pub(crate) mut_bytes_from_bytes: FuncRef,
    pub(crate) mut_bytes_get: FuncRef,
    pub(crate) mut_bytes_set: FuncRef,
    pub(crate) mut_bytes_pop: FuncRef,
    pub(crate) mut_bytes_clear: FuncRef,
    pub(crate) mut_bytes_reserve: FuncRef,
    pub(crate) mut_bytes_to_bytes: FuncRef,
    pub(crate) mut_bytes_extend: FuncRef,
}

pub(crate) struct StatementContext<'a> {
    pub(crate) function: &'a MirFunction,
    pub(crate) types: &'a TypeTable,
    pub(crate) pointer_type: cranelift_codegen::ir::Type,
    pub(crate) string_values:
        &'a mut dyn Iterator<Item = (super::super::context::StringValue, usize)>,
    pub(crate) refs: RuntimeRefs,
    pub(crate) tasks: TaskCodegenContext<'a>,
    pub(crate) continuation_handles: &'a HashMap<MirContinuationId, Value>,
    pub(crate) continuation_spills: &'a HashMap<MirContinuationId, Value>,
    pub(crate) continuation_frames: &'a HashMap<MirContinuationId, Value>,
    pub(crate) continuation_cleanup_drop_refs: &'a HashMap<Type, cranelift_codegen::ir::FuncRef>,
    pub(crate) suspend_pending: Option<Value>,
    pub(crate) pending_abi: bool,
    pub(in crate::codegen::functions) pending_refs: super::super::pending::PendingRefs,
    pub(in crate::codegen::functions) continuation_allocation_refs:
        super::super::ordinary_continuations::ContinuationAllocationRefs,
    pub(crate) continuation_entry_keys: &'a HashMap<MirContinuationId, usize>,
    pub(crate) call_handle_slots: &'a HashMap<MirContinuationId, cranelift_codegen::ir::StackSlot>,
    pub(crate) pending_parent: Option<Value>,
}

#[derive(Clone, Copy)]
pub(crate) struct TaskRuntimeRefs {
    pub(crate) group_new: FuncRef,
    pub(crate) group_free: FuncRef,
    pub(crate) spawn: FuncRef,
    pub(crate) spawn_heap: FuncRef,
    pub(crate) result_pointer: FuncRef,
    pub(crate) join: FuncRef,
    pub(crate) cancel: FuncRef,
    pub(crate) claim_result: FuncRef,
    pub(crate) is_cancelled: FuncRef,
    pub(crate) mark_cancelled_result: FuncRef,
    pub(crate) abort: FuncRef,
    pub(crate) abort_payload: FuncRef,
    pub(crate) failure_operation: FuncRef,
    pub(crate) failure_payload: FuncRef,
    pub(crate) failure_claim: FuncRef,
    pub(crate) failure_rethrow: FuncRef,
    pub(crate) handler_frame_new: FuncRef,
    pub(crate) handler_frame_enter: FuncRef,
    pub(crate) handler_frame_exit: FuncRef,
    pub(crate) handler_frame_free: FuncRef,
    pub(crate) handler_frame_begin_resumption_with_payload: FuncRef,
    pub(crate) handler_frame_begin_resumption_with_payload_env: FuncRef,
    pub(crate) handler_frame_set_resumption_payload_thunk: FuncRef,
    pub(crate) handler_frame_set_resumption_thunk: FuncRef,
    pub(crate) handler_frame_set_resumption_thunk_with_result_env: FuncRef,
    pub(crate) handler_frame_static_thunk: FuncRef,
    pub(crate) handler_frame_forward_thunk: FuncRef,
    pub(crate) handler_frame_transform_i64_thunk: FuncRef,
    pub(crate) handler_frame_dispatch_resumption: FuncRef,
    pub(crate) handler_frame_free_resumption: FuncRef,
    pub(crate) handler_frame_set_resumption_string: FuncRef,
    pub(crate) handler_frame_set_resumption_managed_payload: FuncRef,
    pub(crate) handler_frame_resumption_payload_copy: FuncRef,
    pub(crate) handler_frame_resumption_payload_consume: FuncRef,
    pub(crate) race: FuncRef,
}

pub(crate) struct CompiledTask {
    pub(crate) scope: MirScopeId,
    pub(crate) id: Value,
    pub(crate) result_pointer: Value,
    pub(crate) result_type: Type,
}

pub(crate) struct TaskCodegenContext<'a> {
    pub(crate) refs: TaskRuntimeRefs,
    pub(crate) thunks: HashMap<MirFunctionId, FuncRef>,
    pub(crate) handler_thunks: HashMap<MirFunctionId, FuncRef>,
    pub(crate) result_drops: HashMap<MirFunctionId, FuncRef>,
    pub(crate) failure_drops: HashMap<crate::sema::EffectOperationId, FuncRef>,
    pub(crate) function_types: &'a HashMap<MirFunctionId, FunctionType>,
    pub(crate) groups: HashMap<MirScopeId, Value>,
    pub(crate) tasks: HashMap<MirTaskId, CompiledTask>,
    pub(crate) handler_frames: Vec<Value>,
}

pub(crate) fn declare_task_runtime_refs(
    module: &mut impl Module,
    function: &mut cranelift_codegen::ir::Function,
    ids: crate::codegen::cranelift::TaskRuntimeIds,
) -> TaskRuntimeRefs {
    macro_rules! reference {
        ($field:ident) => {
            module.declare_func_in_func(ids.$field, function)
        };
    }

    TaskRuntimeRefs {
        group_new: reference!(group_new),
        group_free: reference!(group_free),
        spawn: reference!(spawn),
        spawn_heap: reference!(spawn_heap),
        result_pointer: reference!(result_pointer),
        join: reference!(join),
        cancel: reference!(cancel),
        claim_result: reference!(claim_result),
        is_cancelled: reference!(is_cancelled),
        mark_cancelled_result: reference!(mark_cancelled_result),
        abort: reference!(abort),
        abort_payload: reference!(abort_payload),
        failure_operation: reference!(failure_operation),
        failure_payload: reference!(failure_payload),
        failure_claim: reference!(failure_claim),
        failure_rethrow: reference!(failure_rethrow),
        handler_frame_new: reference!(handler_frame_new),
        handler_frame_enter: reference!(handler_frame_enter),
        handler_frame_exit: reference!(handler_frame_exit),
        handler_frame_free: reference!(handler_frame_free),
        handler_frame_begin_resumption_with_payload: reference!(
            handler_frame_begin_resumption_with_payload
        ),
        handler_frame_begin_resumption_with_payload_env: reference!(
            handler_frame_begin_resumption_with_payload_env
        ),
        handler_frame_set_resumption_payload_thunk: reference!(
            handler_frame_set_resumption_payload_thunk
        ),
        handler_frame_set_resumption_thunk: reference!(handler_frame_set_resumption_thunk),
        handler_frame_set_resumption_thunk_with_result_env: reference!(
            handler_frame_set_resumption_thunk_with_result_env
        ),
        handler_frame_static_thunk: reference!(handler_frame_static_thunk),
        handler_frame_forward_thunk: reference!(handler_frame_forward_thunk),
        handler_frame_transform_i64_thunk: reference!(handler_frame_transform_i64_thunk),
        handler_frame_dispatch_resumption: reference!(handler_frame_dispatch_resumption),
        handler_frame_free_resumption: reference!(handler_frame_free_resumption),
        handler_frame_set_resumption_string: reference!(handler_frame_set_resumption_string),
        handler_frame_set_resumption_managed_payload: reference!(
            handler_frame_set_resumption_managed_payload
        ),
        handler_frame_resumption_payload_copy: reference!(handler_frame_resumption_payload_copy),
        handler_frame_resumption_payload_consume: reference!(
            handler_frame_resumption_payload_consume
        ),
        race: reference!(race),
    }
}
