use super::*;
use joky_runtime_abi::symbols::*;

fn declare_import<M: ModuleLifecycle>(
    backend: &mut CraneliftBackend<M>,
    name: &str,
    params: Vec<cranelift_codegen::ir::Type>,
    returns: Vec<cranelift_codegen::ir::Type>,
    call_conv: cranelift_codegen::isa::CallConv,
) -> Result<cranelift_module::FuncId, CodegenError> {
    backend
        .module
        .declare_function(
            name,
            Linkage::Import,
            &Signature {
                params: params.into_iter().map(AbiParam::new).collect(),
                returns: returns.into_iter().map(AbiParam::new).collect(),
                call_conv,
            },
        )
        .map_err(codegen_error)
}

pub(super) struct ContinuationRuntimeIds {
    pub(super) println_id: cranelift_module::FuncId,
    pub(super) print_id: cranelift_module::FuncId,
    pub(super) panic_id: cranelift_module::FuncId,
    pub(super) continuation_resuspend_suspend_id: cranelift_module::FuncId,
    pub(super) continuation_resuspend_suspend_payload_id: cranelift_module::FuncId,
    pub(super) continuation_new_id: cranelift_module::FuncId,
    #[allow(dead_code)] // Kept for the standalone pending-ABI codegen tests.
    pub(super) continuation_begin_function_pending_id: cranelift_module::FuncId,
    pub(super) continuation_complete_function_pending_id: cranelift_module::FuncId,
    pub(super) continuation_start_pending_timer_id: cranelift_module::FuncId,
    pub(super) continuation_start_pending_provider_id: cranelift_module::FuncId,
    pub(super) continuation_register_cleanup_id: cranelift_module::FuncId,
    pub(super) continuation_register_cleanup_region_id: cranelift_module::FuncId,
    pub(super) continuation_alloc_frame_id: cranelift_module::FuncId,
    pub(super) continuation_alloc_result_id: cranelift_module::FuncId,
    pub(super) continuation_alloc_suspend_result_id: cranelift_module::FuncId,
    pub(super) continuation_release_suspend_result_id: cranelift_module::FuncId,
    pub(super) continuation_clear_suspend_cleanups_id: cranelift_module::FuncId,
    pub(super) continuation_frame_pointer_id: cranelift_module::FuncId,
    pub(super) continuation_spill_pointer_id: cranelift_module::FuncId,
    pub(super) continuation_result_pointer_id: cranelift_module::FuncId,
    pub(super) continuation_suspend_result_pointer_id: cranelift_module::FuncId,
    pub(super) continuation_alloc_spill_id: cranelift_module::FuncId,
    pub(super) continuation_free_id: cranelift_module::FuncId,
    pub(super) continuation_set_resume_entry_id: cranelift_module::FuncId,
    pub(super) continuation_set_root_group_id: cranelift_module::FuncId,
    pub(super) continuation_root_group_id: cranelift_module::FuncId,
    pub(super) continuation_set_program_counter_id: cranelift_module::FuncId,
    pub(super) continuation_resume_at_id: cranelift_module::FuncId,
    pub(super) continuation_complete_id: cranelift_module::FuncId,
    pub(super) continuation_complete_suspend_id: cranelift_module::FuncId,
    pub(super) continuation_is_cancelled_id: cranelift_module::FuncId,
}

pub(super) fn declare_continuation_runtime_ids<M: ModuleLifecycle>(
    backend: &mut CraneliftBackend<M>,
    pointer_type: cranelift_codegen::ir::Type,
    call_conv: cranelift_codegen::isa::CallConv,
) -> Result<ContinuationRuntimeIds, CodegenError> {
    use cranelift_codegen::ir::types;

    let pointer = || pointer_type;
    let println_signature = vec![pointer(), pointer()];
    let continuation_handle = vec![pointer()];
    let continuation_operation = vec![pointer(), types::I64];
    let continuation_payload = vec![pointer(), types::I64, pointer(), pointer()];
    let cleanup = vec![pointer(), types::I8, pointer(), pointer()];
    let allocation = vec![pointer(), pointer()];

    Ok(ContinuationRuntimeIds {
        println_id: declare_import(
            backend,
            PRINTLN_SYMBOL,
            println_signature.clone(),
            vec![],
            call_conv,
        )?,
        print_id: declare_import(backend, PRINT_SYMBOL, println_signature, vec![], call_conv)?,
        panic_id: declare_import(
            backend,
            PANIC_SYMBOL,
            vec![pointer(), pointer()],
            vec![],
            call_conv,
        )?,
        continuation_resuspend_suspend_id: declare_import(
            backend,
            CONTINUATION_RESUSPEND_SUSPEND_SYMBOL,
            vec![pointer(), types::I64, types::I64],
            vec![types::I8],
            call_conv,
        )?,
        continuation_resuspend_suspend_payload_id: declare_import(
            backend,
            CONTINUATION_RESUSPEND_SUSPEND_PAYLOAD_SYMBOL,
            continuation_payload,
            vec![types::I8],
            call_conv,
        )?,
        continuation_new_id: declare_import(
            backend,
            CONTINUATION_NEW_SYMBOL,
            vec![types::I64],
            vec![pointer()],
            call_conv,
        )?,
        continuation_begin_function_pending_id: declare_import(
            backend,
            CONTINUATION_BEGIN_FUNCTION_PENDING_SYMBOL,
            continuation_handle.clone(),
            vec![types::I8],
            call_conv,
        )?,
        continuation_complete_function_pending_id: declare_import(
            backend,
            CONTINUATION_COMPLETE_FUNCTION_PENDING_SYMBOL,
            vec![pointer(), pointer(), pointer()],
            vec![types::I8],
            call_conv,
        )?,
        continuation_start_pending_timer_id: declare_import(
            backend,
            joky_runtime_abi::symbols::CONTINUATION_START_PENDING_TIMER_SYMBOL,
            vec![pointer(), types::I64, types::I64, pointer()],
            vec![types::I8],
            call_conv,
        )?,
        continuation_start_pending_provider_id: declare_import(
            backend,
            joky_runtime_abi::symbols::CONTINUATION_START_PENDING_PROVIDER_SYMBOL,
            vec![pointer(), types::I64, pointer(), pointer(), pointer()],
            vec![types::I8],
            call_conv,
        )?,
        continuation_register_cleanup_id: declare_import(
            backend,
            CONTINUATION_REGISTER_CLEANUP_SYMBOL,
            cleanup.clone(),
            vec![types::I8],
            call_conv,
        )?,
        continuation_register_cleanup_region_id: declare_import(
            backend,
            CONTINUATION_REGISTER_CLEANUP_REGION_SYMBOL,
            cleanup,
            vec![types::I8],
            call_conv,
        )?,
        continuation_alloc_frame_id: declare_import(
            backend,
            CONTINUATION_ALLOC_FRAME_SYMBOL,
            allocation.clone(),
            vec![pointer()],
            call_conv,
        )?,
        continuation_alloc_result_id: declare_import(
            backend,
            CONTINUATION_ALLOC_RESULT_SYMBOL,
            allocation.clone(),
            vec![pointer()],
            call_conv,
        )?,
        continuation_alloc_suspend_result_id: declare_import(
            backend,
            CONTINUATION_ALLOC_SUSPEND_RESULT_SYMBOL,
            allocation.clone(),
            vec![pointer()],
            call_conv,
        )?,
        continuation_release_suspend_result_id: declare_import(
            backend,
            CONTINUATION_RELEASE_SUSPEND_RESULT_SYMBOL,
            continuation_handle.clone(),
            vec![types::I8],
            call_conv,
        )?,
        continuation_clear_suspend_cleanups_id: declare_import(
            backend,
            CONTINUATION_CLEAR_SUSPEND_CLEANUPS_SYMBOL,
            continuation_handle.clone(),
            vec![types::I8],
            call_conv,
        )?,
        continuation_frame_pointer_id: declare_import(
            backend,
            CONTINUATION_FRAME_POINTER_SYMBOL,
            continuation_handle.clone(),
            vec![pointer()],
            call_conv,
        )?,
        continuation_spill_pointer_id: declare_import(
            backend,
            joky_runtime_abi::symbols::CONTINUATION_SPILL_POINTER_SYMBOL,
            continuation_handle.clone(),
            vec![pointer()],
            call_conv,
        )?,
        continuation_result_pointer_id: declare_import(
            backend,
            CONTINUATION_RESULT_POINTER_SYMBOL,
            continuation_handle.clone(),
            vec![pointer()],
            call_conv,
        )?,
        continuation_suspend_result_pointer_id: declare_import(
            backend,
            CONTINUATION_SUSPEND_RESULT_POINTER_SYMBOL,
            continuation_handle.clone(),
            vec![pointer()],
            call_conv,
        )?,
        continuation_alloc_spill_id: declare_import(
            backend,
            CONTINUATION_ALLOC_SPILL_SYMBOL,
            allocation.clone(),
            vec![pointer()],
            call_conv,
        )?,
        continuation_free_id: declare_import(
            backend,
            CONTINUATION_FREE_SYMBOL,
            continuation_handle.clone(),
            vec![],
            call_conv,
        )?,
        continuation_set_resume_entry_id: declare_import(
            backend,
            CONTINUATION_SET_RESUME_ENTRY_SYMBOL,
            vec![pointer(), pointer()],
            vec![types::I8],
            call_conv,
        )?,
        continuation_set_root_group_id: declare_import(
            backend,
            CONTINUATION_SET_ROOT_GROUP_SYMBOL,
            vec![pointer(), pointer()],
            vec![types::I8],
            call_conv,
        )?,
        continuation_root_group_id: declare_import(
            backend,
            CONTINUATION_ROOT_GROUP_SYMBOL,
            continuation_handle.clone(),
            vec![pointer()],
            call_conv,
        )?,
        continuation_set_program_counter_id: declare_import(
            backend,
            CONTINUATION_SET_PROGRAM_COUNTER_SYMBOL,
            vec![pointer(), pointer()],
            vec![types::I8],
            call_conv,
        )?,
        continuation_resume_at_id: declare_import(
            backend,
            CONTINUATION_RESUME_AT_SYMBOL,
            vec![pointer(), pointer()],
            vec![types::I8],
            call_conv,
        )?,
        continuation_complete_id: declare_import(
            backend,
            CONTINUATION_COMPLETE_SYMBOL,
            continuation_handle.clone(),
            vec![types::I8],
            call_conv,
        )?,
        continuation_complete_suspend_id: declare_import(
            backend,
            CONTINUATION_COMPLETE_SUSPEND_SYMBOL,
            continuation_operation,
            vec![types::I8],
            call_conv,
        )?,
        continuation_is_cancelled_id: declare_import(
            backend,
            CONTINUATION_IS_CANCELLED_SYMBOL,
            continuation_handle,
            vec![types::I8],
            call_conv,
        )?,
    })
}

pub(super) struct BasicRuntimeIds {
    pub(super) allocate_id: cranelift_module::FuncId,
    pub(super) closure_allocate_id: cranelift_module::FuncId,
    pub(super) dup_id: cranelift_module::FuncId,
    pub(super) drop_id: cranelift_module::FuncId,
    pub(super) string_from_id: cranelift_module::FuncId,
    pub(super) bytes_from_data_id: cranelift_module::FuncId,
    pub(super) string_len_id: cranelift_module::FuncId,
    pub(super) string_c_string_check_id: cranelift_module::FuncId,
    pub(super) string_from_cstr_id: cranelift_module::FuncId,
    pub(super) c_alloc_id: cranelift_module::FuncId,
    pub(super) c_free_id: cranelift_module::FuncId,
    pub(super) show_i64_id: cranelift_module::FuncId,
    pub(super) debug_path_id: cranelift_module::FuncId,
    pub(super) debug_path_status_id: cranelift_module::FuncId,
    pub(super) debug_native_id_id: cranelift_module::FuncId,
    pub(super) debug_string_id: cranelift_module::FuncId,
    pub(super) debug_bytes_id: cranelift_module::FuncId,
    pub(super) debug_duration_id: cranelift_module::FuncId,
    pub(super) echo_id: cranelift_module::FuncId,
    pub(super) show_u64_id: cranelift_module::FuncId,
    pub(super) show_f64_id: cranelift_module::FuncId,
    pub(super) show_bool_id: cranelift_module::FuncId,
    pub(super) string_concat_id: cranelift_module::FuncId,
    pub(super) string_eq_id: cranelift_module::FuncId,
    pub(super) string_compare_id: cranelift_module::FuncId,
    pub(super) string_starts_with_id: cranelift_module::FuncId,
    pub(super) string_ends_with_id: cranelift_module::FuncId,
    pub(super) string_contains_id: cranelift_module::FuncId,
    pub(super) string_scalar_count_id: cranelift_module::FuncId,
    pub(super) string_grapheme_count_id: cranelift_module::FuncId,
    pub(super) string_is_ascii_id: cranelift_module::FuncId,
    pub(super) string_trim_id: cranelift_module::FuncId,
    pub(super) string_to_upper_id: cranelift_module::FuncId,
    pub(super) string_to_lower_id: cranelift_module::FuncId,
    pub(super) string_split_id: cranelift_module::FuncId,
    pub(super) path_call_id: cranelift_module::FuncId,
    pub(super) string_replace_id: cranelift_module::FuncId,
    pub(super) string_get_byte_id: cranelift_module::FuncId,
    pub(super) string_slice_id: cranelift_module::FuncId,
}

pub(super) fn declare_basic_runtime_ids<M: ModuleLifecycle>(
    backend: &mut CraneliftBackend<M>,
    pointer_type: cranelift_codegen::ir::Type,
    call_conv: cranelift_codegen::isa::CallConv,
) -> Result<BasicRuntimeIds, CodegenError> {
    use cranelift_codegen::ir::types;

    let pointer = || pointer_type;
    let unary_pointer = vec![pointer()];
    let string_pair = vec![pointer(), pointer()];
    let string_quad = vec![pointer(); 4];

    Ok(BasicRuntimeIds {
        allocate_id: declare_import(
            backend,
            ALLOC_OBJECT_SYMBOL,
            vec![types::I8, pointer(), pointer()],
            vec![pointer()],
            call_conv,
        )?,
        closure_allocate_id: declare_import(
            backend,
            ALLOC_CLOSURE_ENVIRONMENT_SYMBOL,
            vec![pointer(); 3],
            vec![pointer()],
            call_conv,
        )?,
        dup_id: declare_import(
            backend,
            DUP_SYMBOL,
            unary_pointer.clone(),
            vec![pointer()],
            call_conv,
        )?,
        drop_id: declare_import(
            backend,
            DROP_SYMBOL,
            unary_pointer.clone(),
            vec![],
            call_conv,
        )?,
        bytes_from_data_id: declare_import(
            backend,
            BYTES_FROM_DATA_SYMBOL,
            string_pair.clone(),
            vec![pointer()],
            call_conv,
        )?,
        string_from_id: declare_import(
            backend,
            STRING_FROM_UTF8_SYMBOL,
            string_pair.clone(),
            vec![pointer()],
            call_conv,
        )?,
        string_len_id: declare_import(
            backend,
            STRING_LEN_SYMBOL,
            unary_pointer.clone(),
            vec![pointer()],
            call_conv,
        )?,
        string_c_string_check_id: declare_import(
            backend,
            STRING_C_STRING_CHECK_SYMBOL,
            string_pair.clone(),
            vec![],
            call_conv,
        )?,
        string_from_cstr_id: declare_import(
            backend,
            STRING_FROM_CSTR_SYMBOL,
            unary_pointer.clone(),
            vec![pointer()],
            call_conv,
        )?,
        c_alloc_id: declare_import(
            backend,
            C_ALLOC_SYMBOL,
            unary_pointer.clone(),
            vec![pointer()],
            call_conv,
        )?,
        c_free_id: declare_import(
            backend,
            C_FREE_SYMBOL,
            unary_pointer.clone(),
            vec![],
            call_conv,
        )?,
        show_i64_id: declare_import(
            backend,
            SHOW_I64_SYMBOL,
            vec![types::I64],
            vec![pointer()],
            call_conv,
        )?,
        debug_string_id: declare_import(
            backend,
            DEBUG_STRING_SYMBOL,
            string_pair.clone(),
            vec![pointer()],
            call_conv,
        )?,
        debug_bytes_id: declare_import(
            backend,
            DEBUG_BYTES_SYMBOL,
            vec![pointer()],
            vec![pointer()],
            call_conv,
        )?,
        debug_duration_id: declare_import(
            backend,
            DEBUG_DURATION_SYMBOL,
            vec![types::I64],
            vec![pointer()],
            call_conv,
        )?,
        echo_id: declare_import(backend, ECHO_SYMBOL, string_quad.clone(), vec![], call_conv)?,
        debug_path_id: declare_import(
            backend,
            DEBUG_PATH_SYMBOL,
            vec![pointer(), pointer()],
            vec![pointer()],
            call_conv,
        )?,
        debug_path_status_id: declare_import(
            backend,
            DEBUG_PATH_STATUS_SYMBOL,
            vec![pointer()],
            vec![types::I32],
            call_conv,
        )?,
        debug_native_id_id: declare_import(
            backend,
            DEBUG_NATIVE_ID_SYMBOL,
            vec![pointer()],
            vec![types::I64],
            call_conv,
        )?,
        show_u64_id: declare_import(
            backend,
            SHOW_U64_SYMBOL,
            vec![types::I64],
            vec![pointer()],
            call_conv,
        )?,
        show_f64_id: declare_import(
            backend,
            SHOW_F64_SYMBOL,
            vec![types::F64],
            vec![pointer()],
            call_conv,
        )?,
        show_bool_id: declare_import(
            backend,
            SHOW_BOOL_SYMBOL,
            vec![types::I8],
            vec![pointer()],
            call_conv,
        )?,
        string_concat_id: declare_import(
            backend,
            STRING_CONCAT_SYMBOL,
            string_quad.clone(),
            vec![pointer()],
            call_conv,
        )?,
        string_compare_id: declare_import(
            backend,
            STRING_COMPARE_SYMBOL,
            string_quad.clone(),
            vec![types::I32],
            call_conv,
        )?,
        string_eq_id: declare_import(
            backend,
            STRING_EQ_SYMBOL,
            string_quad.clone(),
            vec![types::I8],
            call_conv,
        )?,
        string_starts_with_id: declare_import(
            backend,
            STRING_STARTS_WITH_SYMBOL,
            string_quad.clone(),
            vec![types::I8],
            call_conv,
        )?,
        string_ends_with_id: declare_import(
            backend,
            STRING_ENDS_WITH_SYMBOL,
            string_quad.clone(),
            vec![types::I8],
            call_conv,
        )?,
        string_contains_id: declare_import(
            backend,
            STRING_CONTAINS_SYMBOL,
            string_quad,
            vec![types::I8],
            call_conv,
        )?,
        string_scalar_count_id: declare_import(
            backend,
            STRING_SCALAR_COUNT_SYMBOL,
            string_pair.clone(),
            vec![pointer()],
            call_conv,
        )?,
        string_grapheme_count_id: declare_import(
            backend,
            STRING_GRAPHEME_COUNT_SYMBOL,
            string_pair.clone(),
            vec![pointer()],
            call_conv,
        )?,
        string_is_ascii_id: declare_import(
            backend,
            STRING_IS_ASCII_SYMBOL,
            string_pair.clone(),
            vec![types::I8],
            call_conv,
        )?,
        string_trim_id: declare_import(
            backend,
            STRING_TRIM_SYMBOL,
            string_pair.clone(),
            vec![pointer()],
            call_conv,
        )?,
        string_to_upper_id: declare_import(
            backend,
            STRING_TO_UPPER_SYMBOL,
            string_pair.clone(),
            vec![pointer()],
            call_conv,
        )?,
        string_to_lower_id: declare_import(
            backend,
            STRING_TO_LOWER_SYMBOL,
            string_pair.clone(),
            vec![pointer()],
            call_conv,
        )?,
        path_call_id: declare_import(
            backend,
            PATH_CALL_SYMBOL,
            vec![types::I8, pointer(), pointer()],
            vec![],
            call_conv,
        )?,
        string_split_id: declare_import(
            backend,
            STRING_SPLIT_SYMBOL,
            vec![pointer(), pointer(), pointer(), pointer()],
            vec![pointer()],
            call_conv,
        )?,
        string_replace_id: declare_import(
            backend,
            STRING_REPLACE_SYMBOL,
            vec![
                pointer(),
                pointer(),
                pointer(),
                pointer(),
                pointer(),
                pointer(),
            ],
            vec![pointer()],
            call_conv,
        )?,
        string_get_byte_id: declare_import(
            backend,
            STRING_GET_BYTE_SYMBOL,
            vec![pointer(), pointer(), pointer(), pointer()],
            vec![types::I8],
            call_conv,
        )?,
        string_slice_id: declare_import(
            backend,
            STRING_SLICE_SYMBOL,
            vec![pointer(), pointer(), pointer(), pointer()],
            vec![pointer()],
            call_conv,
        )?,
    })
}

pub(super) fn declare_task_runtime_ids<M: ModuleLifecycle>(
    backend: &mut CraneliftBackend<M>,
    pointer_type: cranelift_codegen::ir::Type,
    call_conv: cranelift_codegen::isa::CallConv,
) -> Result<TaskRuntimeIds, CodegenError> {
    use cranelift_codegen::ir::types;

    let pointer = || pointer_type;
    let group_handle = vec![pointer()];
    let task_handle = vec![pointer(), types::I64];
    let result_pointer = vec![pointer()];
    let handler_frame = vec![pointer()];

    Ok(TaskRuntimeIds {
        group_cancel_free: declare_import(
            backend,
            TASK_GROUP_CANCEL_FREE_SYMBOL,
            vec![pointer()],
            vec![],
            call_conv,
        )?,
        group_new: declare_import(
            backend,
            TASK_GROUP_NEW_SYMBOL,
            vec![pointer()],
            vec![pointer()],
            call_conv,
        )?,
        group_free: declare_import(
            backend,
            TASK_GROUP_FREE_SYMBOL,
            group_handle.clone(),
            vec![],
            call_conv,
        )?,
        spawn: declare_import(
            backend,
            TASK_SPAWN_SYMBOL,
            vec![pointer(); 3],
            vec![types::I64],
            call_conv,
        )?,
        spawn_heap: declare_import(
            backend,
            TASK_SPAWN_HEAP_SYMBOL,
            vec![pointer(); 6],
            vec![types::I64],
            call_conv,
        )?,
        join: declare_import(
            backend,
            TASK_JOIN_SYMBOL,
            task_handle.clone(),
            vec![],
            call_conv,
        )?,
        cancel: declare_import(backend, TASK_CANCEL_SYMBOL, task_handle, vec![], call_conv)?,
        race: declare_import(
            backend,
            TASK_RACE_SYMBOL,
            vec![pointer(); 5],
            vec![types::I64],
            call_conv,
        )?,
        claim_result: declare_import(
            backend,
            TASK_CLAIM_RESULT_SYMBOL,
            vec![pointer(), types::I64],
            vec![],
            call_conv,
        )?,
        result_pointer: declare_import(
            backend,
            TASK_RESULT_POINTER_SYMBOL,
            vec![pointer(), types::I64],
            vec![pointer()],
            call_conv,
        )?,
        is_cancelled: declare_import(
            backend,
            TASK_IS_CANCELLED_SYMBOL,
            vec![],
            vec![types::I8],
            call_conv,
        )?,
        mark_cancelled_result: declare_import(
            backend,
            TASK_MARK_CANCELLED_RESULT_SYMBOL,
            vec![],
            vec![],
            call_conv,
        )?,
        abort: declare_import(
            backend,
            TASK_ABORT_SYMBOL,
            vec![types::I64],
            vec![],
            call_conv,
        )?,
        abort_payload: declare_import(
            backend,
            TASK_ABORT_PAYLOAD_SYMBOL,
            vec![types::I64, pointer(), pointer(), pointer()],
            vec![],
            call_conv,
        )?,
        failure_operation: declare_import(
            backend,
            TASK_FAILURE_OPERATION_SYMBOL,
            group_handle.clone(),
            vec![types::I64],
            call_conv,
        )?,
        failure_payload: declare_import(
            backend,
            TASK_GROUP_FAILURE_PAYLOAD_SYMBOL,
            group_handle.clone(),
            result_pointer,
            call_conv,
        )?,
        failure_claim: declare_import(
            backend,
            TASK_FAILURE_CLAIM_SYMBOL,
            group_handle.clone(),
            vec![],
            call_conv,
        )?,
        failure_rethrow: declare_import(
            backend,
            TASK_FAILURE_RETHROW_SYMBOL,
            group_handle,
            vec![],
            call_conv,
        )?,
        handler_frame_new: declare_import(
            backend,
            HANDLER_FRAME_NEW_SYMBOL,
            vec![pointer(); 2],
            vec![pointer()],
            call_conv,
        )?,
        handler_frame_enter: declare_import(
            backend,
            HANDLER_FRAME_ENTER_SYMBOL,
            handler_frame.clone(),
            vec![types::I8],
            call_conv,
        )?,
        handler_frame_exit: declare_import(
            backend,
            HANDLER_FRAME_EXIT_SYMBOL,
            handler_frame.clone(),
            vec![types::I8],
            call_conv,
        )?,
        handler_frame_free: declare_import(
            backend,
            HANDLER_FRAME_FREE_SYMBOL,
            handler_frame.clone(),
            vec![],
            call_conv,
        )?,
        handler_frame_begin_resumption_with_payload: declare_import(
            backend,
            HANDLER_FRAME_BEGIN_RESUMPTION_HANDLE_WITH_PAYLOAD_SYMBOL,
            vec![types::I64, pointer(), pointer()],
            vec![pointer()],
            call_conv,
        )?,
        handler_frame_begin_resumption_with_payload_env: declare_import(
            backend,
            HANDLER_FRAME_BEGIN_RESUMPTION_HANDLE_WITH_PAYLOAD_ENV_SYMBOL,
            vec![types::I64, pointer(), pointer(), pointer(), pointer()],
            vec![pointer()],
            call_conv,
        )?,
        handler_frame_free_resumption: declare_import(
            backend,
            HANDLER_FRAME_FREE_RESUMPTION_HANDLE_SYMBOL,
            handler_frame.clone(),
            vec![],
            call_conv,
        )?,
        handler_frame_set_resumption_string: declare_import(
            backend,
            HANDLER_FRAME_SET_RESUMPTION_STRING_SYMBOL,
            vec![pointer(), types::I64, pointer(), pointer()],
            vec![types::I8],
            call_conv,
        )?,
        handler_frame_set_resumption_managed_payload: declare_import(
            backend,
            HANDLER_FRAME_SET_RESUMPTION_MANAGED_PAYLOAD_SYMBOL,
            vec![pointer(); 6],
            vec![types::I8],
            call_conv,
        )?,
        handler_frame_resumption_payload_copy: declare_import(
            backend,
            HANDLER_FRAME_RESUMPTION_PAYLOAD_COPY_SYMBOL,
            vec![pointer(); 3],
            vec![pointer()],
            call_conv,
        )?,
        handler_frame_resumption_payload_consume: declare_import(
            backend,
            HANDLER_FRAME_RESUMPTION_PAYLOAD_CONSUME_SYMBOL,
            handler_frame.clone(),
            vec![types::I8],
            call_conv,
        )?,
        handler_frame_set_resumption_payload_thunk: declare_import(
            backend,
            HANDLER_FRAME_SET_RESUMPTION_PAYLOAD_THUNK_SYMBOL,
            vec![pointer(), types::I64, pointer(), pointer()],
            vec![types::I8],
            call_conv,
        )?,
        handler_frame_set_resumption_thunk: declare_import(
            backend,
            HANDLER_FRAME_SET_RESUMPTION_THUNK_SYMBOL,
            vec![pointer(); 6],
            vec![types::I8],
            call_conv,
        )?,
        handler_frame_set_resumption_thunk_with_result_env: declare_import(
            backend,
            HANDLER_FRAME_SET_RESUMPTION_THUNK_WITH_RESULT_ENV_SYMBOL,
            vec![pointer(); 10],
            vec![types::I8],
            call_conv,
        )?,
        handler_frame_dispatch_resumption: declare_import(
            backend,
            HANDLER_FRAME_DISPATCH_RESUMPTION_HANDLE_SYMBOL,
            handler_frame.clone(),
            vec![types::I8],
            call_conv,
        )?,
        handler_frame_static_thunk: declare_import(
            backend,
            HANDLER_FRAME_STATIC_THUNK_SYMBOL,
            handler_frame.clone(),
            vec![types::I8],
            call_conv,
        )?,
        handler_frame_forward_thunk: declare_import(
            backend,
            HANDLER_FRAME_FORWARD_THUNK_SYMBOL,
            handler_frame.clone(),
            vec![types::I8],
            call_conv,
        )?,
        handler_frame_transform_i64_thunk: declare_import(
            backend,
            HANDLER_FRAME_TRANSFORM_I64_THUNK_SYMBOL,
            handler_frame,
            vec![types::I8],
            call_conv,
        )?,
    })
}
