#!/usr/bin/env python3
"""Generate fixed Unicode 3.2 normalization and RFC 3454 property data.

Uses Python's explicitly versioned ucd_3_2_0 and stringprep, never the
interpreter's current Unicode database. No network or third-party dependency.
Run with --check to verify the committed data byte-for-byte.
"""
import argparse
import hashlib
from pathlib import Path
import stringprep
import unicodedata

ROOT = Path(__file__).resolve().parent.parent
UCD = unicodedata.ucd_3_2_0


def ranges(predicate):
    result = []
    start = None
    for cp in range(0x110001):
        present = cp < 0x110000 and predicate(chr(cp))
        if present and start is None:
            start = cp
        elif not present and start is not None:
            result.append((start, cp - 1))
            start = None
    return ''.join(f'{lo:06x}{hi:06x}' for lo, hi in result)


def generate():
    assert UCD.unidata_version == '3.2.0'
    assert stringprep.unicodedata.unidata_version == '3.2.0'
    decompositions, scalars, combining, compositions = [], [], [], []
    for cp in range(0x110000):
        char = chr(cp)
        ccc = UCD.combining(char)
        if ccc:
            combining.append(f'{cp:06x}{ccc:02x}')
        # Hangul decomposition/composition is algorithmic at runtime.
        if not 0xac00 <= cp <= 0xd7a3:
            normalized = UCD.normalize('NFKD', char)
            if normalized != char:
                assert len(normalized) < 256
                decompositions.append(f'{cp:06x}{len(scalars):06x}{len(normalized):02x}')
                scalars.extend(f'{ord(c):06x}' for c in normalized)
        raw = UCD.decomposition(char)
        if raw and not raw.startswith('<'):
            pair = [int(value, 16) for value in raw.split()]
            if len(pair) == 2 and UCD.normalize('NFC', ''.join(map(chr, pair))) == char:
                compositions.append((pair[0], pair[1], cp))
    prohibited = ['c12', 'c21', 'c22', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9']
    tables = {
        'decompositions': ''.join(decompositions),
        'decomposed_scalars': ''.join(scalars),
        'combining': ''.join(combining),
        'compositions': ''.join(f'{a:06x}{b:06x}{c:06x}' for a, b, c in sorted(compositions)),
        'spaces': ranges(stringprep.in_table_c12),
        'mapped_to_nothing': ranges(stringprep.in_table_b1),
        'unassigned': ranges(stringprep.in_table_a1),
        'prohibited': ranges(lambda c: any(getattr(stringprep, 'in_table_' + t)(c) for t in prohibited)),
        'randal': ranges(stringprep.in_table_d1),
        'left_to_right': ranges(stringprep.in_table_d2),
    }
    output = [
        '// Generated by scripts/generate-unicode32.py; do not edit.',
        '// Unicode 3.2.0 / RFC 3454. See docs/stdlib/saslprep.md for provenance.',
        '// ASCII hex records decoded in Joky; callers retain tables per operation.',
        '// Layouts: decomp=(cp:6, offset:6, length:2); scalars=6; ccc=(cp:6, class:2);',
        '// compose=(first:6, second:6, result:6); ranges=(start:6, end:6).',
        '',
    ]
    for name, data in tables.items():
        digest = hashlib.sha256(data.encode('ascii')).hexdigest()
        output.extend([f'// {len(data)} ASCII bytes; SHA-256 {digest}',
                       f'pub fn {name}() -> String {{ "{data}" }}', ''])
    return '\n'.join(output)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT / 'std/joky/unicode/tables32.jk'
    generated = generate()
    if args.check:
        if not target.is_file() or target.read_text() != generated:
            raise SystemExit('Unicode 3.2 tables differ; run scripts/generate-unicode32.py')
        print('Unicode 3.2 tables match the pinned generator')
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(generated)
        print(f'Generated {target.relative_to(ROOT)} ({len(generated)} bytes)')


if __name__ == '__main__':
    main()
